### ISSUE TITLE
Default UDP socket for user-traffic of a Subscriber

### ISSUE THREAD

**Issue by JerrySciangula** [eProsima/Fast-DDS-docs#362] opened 2022-03-24 10:47 UTC
Hi all,

imagine a scenario with a 2 DomainParticipants: 1 Publisher with multiple DataWriters publishing data over different Topics and 1 Subscriber, including multiple DataReaders, each subscribed to the DataWriters in a 1-to-1 fashion.

The best-effort sending of DataWriters data is managed by the Asynchronous thread using the FlowController policy HIGH_PRIORITY. So, each DataWriter is associated to a certain priority and the output flow is ordered according to this priority.

Now, for the Subscriber, if you disable the SHM transport, FastDDS by default creates 3 threads listening on UDP sockets (2 for meta-traffic data and 1 for user-traffic).

Regarding data user-traffic:

1) Is all the traffic (DataWriters' data) handled in FIFO order by the single UDP socket?
2) Is there a way to guarantee that DataWriters' data is received in the same order it has been sent?
3) Can I create multiple user-traffic UDP threads to differentiate and manage the prioritized user-traffic?

Thank you in advance

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-24 11:22
This is a duplicate of eProsima/Fast-DDS#2599

**Closed by JLBuenoLopez-eProsima** 2022-03-24 11:22 UTC
